### ISSUE TITLE
从source中取得相同id的部分字段到destination中？

### ISSUE THREAD

**Issue by zealinux** [hooopo/kiba-plus#15]
source和destination不是一个数据库，source是MySQL，destination是Postgres。
他们有部分相同的id（uuid），
如果相同的id，则取source中的某几个字段，update到destination。
如果没有就不操作。只更新，不新插入。

具体有什么好的思路，尤其是kiba（-plus）中怎么比较id？

**Comment by hooopo** [comment]
不好意思，才看到。

这种情况一般是先把source拉到destination，再同库内做更新。
还有一种办法是，单独建立一个source的client（ActiveRecord or MySql驱动），在Transform里做处理，但效率不会很高。
