### ISSUE TITLE
Problem with NULL values (PostgreSQL to PostgreSQL ETL)

### ISSUE THREAD

**Issue by mendesds** [hooopo/kiba-plus#17]
Hello everybody.

First of all, congratulations for this very useful gem :clap: :clap: 

I had this small issue when fetching data from a PostgreSQL database to another PostgresSQL, and I found a workaround that I could do in my code.

The problem occurs when my query on target database returns NULL values, and this error is returned:

```
ERROR:  invalid input syntax for integer: "" (PG::InvalidTextRepresentation)
CONTEXT:  COPY XXX_staging, line 1, column YYY_id: ""
```
`XXX` and `YYY` are the destination table and the destination column.

The fix:

I created a class that inherits Kiba::Plus::Destination::PgBulk2, overriding the implementation of `bulk_sql_with_incremental` and `bulk_sql_with_non_incremental` to remove the `NULL '\\N'` line, resulting in something like:

```
module ETL
  module Destinations
    class PgBulk2 < Kiba::Plus::Destination::PgBulk2
      def bulk_sql_with_incremental
        sql = <<-SQL
        COPY #{staging_table_name} (#{columns.join(', ')})
          FROM STDIN
            WITH
              DELIMITER ','
              CSV
        SQL
        format_sql sql
      end

      def bulk_sql_with_non_incremental
        sql = <<-SQL
        COPY #{table_name} (#{columns.join(', ')})
          FROM STDIN
            WITH
              DELIMITER ','
              CSV
        SQL
        format_sql sql
      end
    end
  end
end
```

The main question is about this line that I removed from my side (`NULL '\\N'`), in witch situations is it needed, and if could this fix break other cases?

**Comment by mendesds** [comment]
The version of kiba-plus and kiba I'm using are:
```
kiba-plus (1.0.0)
      kiba (~> 2.0.0)
```

**Comment by hooopo** [comment]
you should add a transform 

```
def self.re_nil(row, *fields)
    fields.each do |field|
      row[field] = row[field].blank? ?  '\\N' : row[field]
    end
  end
```

https://www.postgresql.org/docs/9.2/sql-copy.html

> Specifies the string that represents a null value. The default is \N (backslash-N) in text format, and an unquoted empty string in CSV format. You might prefer an empty string even in text format for cases where you don't want to distinguish nulls from empty strings. This option is not allowed when using binary format.
